meta_product_name: "Rungis Market"
meta_title: "Rungis Market - Des fruits et légumes frais, pas cher, juste en bas de chez toi !"
meta_description: "Service d'achat et de livraison par point relais de fruits et légumes frais"
meta_image: "logo-rungis.png" # should exist in `app/assets/images/`
